### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by hinshun** [IronWarrior/SuperCharacterController#17]
Hi there,

Just reporting some unused code that I found:

https://github.com/IronWarrior/SuperCharacterController/blob/master/Assets/SuperCharacterController/Core/SuperCharacterController.cs#L800-L805
Which I think repeats the function of this one, other than that it returns the vector, which can be done with IsGrounded already: https://github.com/IronWarrior/SuperCharacterController/blob/master/Assets/SuperCharacterController/Core/SuperCharacterController.cs#L712-L716

As far as I can tell, currentlyClampedTo is always null:
https://github.com/IronWarrior/SuperCharacterController/blob/master/Assets/SuperCharacterController/Core/SuperCharacterController.cs#L86

A repeat of SuperGround's Distance function:
https://github.com/IronWarrior/SuperCharacterController/blob/master/Assets/SuperCharacterController/Core/SuperCharacterController.cs#L807-L810

**Comment by IronWarrior** [comment]
No idea how Normal() survived so long, since I think I wrote it while doing initial development on the new grounding. Removed it. Also removed HitDistance().

currentlyClampedTo is always null within the controller, as it is intended to allow users to manually select what the controller is to be clamped to (as it is a property).

Thanks for the proofreading! I pushed all the changes in the same commit to the master.
